# Site settings
title: Ziyu Wang
tagline: By Pixelarity
description: > # this means to ignore newlines until "baseurl:"
  Ziyu Wang's portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ziyuwang11.github.io/" # the base hostname & protocol for your site

# Plugins
gems: ["jekyll-paginate"]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"